# Generated by Django 6.0.7 on 2026-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingemailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
