# Generated by Django 6.0.7 on 2026-07-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('public', 'Public'), ('private', 'Private'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('clef_range', models.CharField(max_length=6, null=True)),
                ('composer', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('style', models.CharField(choices=[('western_classical', 'Western Classical'), ('musical_theatre', 'Musical Theatre'), ('commercial_music', 'Commercial Music'), ('choral', 'Choral'), ('other', 'Other')], max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('midi_file', models.FileField(blank=True, null=True, upload_to='midi/')),
                ('q1_freq', models.FloatField()),
                ('q1_pitch', models.CharField(max_length=2)),
                ('q1_octave', models.IntegerField()),
                ('q3_freq', models.FloatField()),
                ('q3_pitch', models.CharField(max_length=2)),
                ('q3_octave', models.IntegerField()),
                ('cycle_dose', models.FloatField()),
                ('time_dose', models.FloatField()),
                ('rest_time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('median_freq', models.FloatField()),
                ('min_freq', models.FloatField()),
                ('max_freq', models.FloatField()),
                ('hvhp_time_dose', models.FloatField()),
                ('hvmp_time_dose', models.FloatField()),
                ('hvlp_time_dose', models.FloatField()),
                ('mvhp_time_dose', models.FloatField()),
                ('mvmp_time_dose', models.FloatField()),
                ('mvlp_time_dose', models.FloatField()),
                ('lvhp_time_dose', models.FloatField()),
                ('lvmp_time_dose', models.FloatField()),
                ('lvlp_time_dose', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
